In [1]:
import os
import numpy as np

In [2]:
# QUESTIN 1

In [3]:
arr= np.arange(1,26)

In [4]:
arr=arr.reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [5]:
arr[0:,0:1]

array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])

In [6]:
arr[-1:,0:]

array([[21, 22, 23, 24, 25]])

In [7]:
np.diag(arr)

array([ 1,  7, 13, 19, 25])

In [8]:
# QUESTION 2

In [9]:
arr1=np.array([[1,2,3],
              [4,5,6]])
arr2=np.array([[7,8,9],
               [10,11,12]])
c=arr1+arr2
c

array([[ 8, 10, 12],
       [14, 16, 18]])

In [10]:
d=arr1*arr2
d

array([[ 7, 16, 27],
       [40, 55, 72]])

In [11]:
e=arr1-arr2
e

array([[-6, -6, -6],
       [-6, -6, -6]])

In [12]:
# QUESTION 3

In [13]:
arr=np.arange(1,101)
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [14]:
value=arr[arr%3==0]
value

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [15]:
# QUESTION 4

In [16]:
arr=np.arange(1,17)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [17]:
arr= arr.reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [18]:
x=arr[arr%2==0]=0
print(arr)

[[ 1  0  3  0]
 [ 5  0  7  0]
 [ 9  0 11  0]
 [13  0 15  0]]


In [19]:
# QUESTION 5

In [20]:
arr=np.arange(26)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])

In [21]:
x=arr.min()
x

np.int64(0)

In [22]:
x=arr.max()
x

np.int64(25)

In [23]:
y=np.mean(arr)
y

np.float64(12.5)

In [24]:
z=np.median(arr)
z

np.float64(12.5)

In [25]:
# QUESTION 6

In [26]:
import numpy as np

In [27]:
arr=np.random.randint(1,100,20)
arr

array([94, 53,  8, 94, 37, 24, 16, 92, 91, 99, 27, 28, 46, 57, 31, 40, 71,
       93, 53, 69], dtype=int32)

In [28]:
arr=np.sort(arr)
print(arr)

[ 8 16 24 27 28 31 37 40 46 53 53 57 69 71 91 92 93 94 94 99]


In [29]:
arr=np.sort(arr)[::-1]
arr

array([99, 94, 94, 93, 92, 91, 71, 69, 57, 53, 53, 46, 40, 37, 31, 28, 27,
       24, 16,  8], dtype=int32)

In [30]:
# QUESTION 7

In [31]:
arr=np.arange(1,37)


In [32]:
arr=arr.reshape(6,6)

In [33]:
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [34]:
np.diag(arr)

array([ 1,  8, 15, 22, 29, 36])

In [35]:
np.triu(arr)

array([[ 1,  2,  3,  4,  5,  6],
       [ 0,  8,  9, 10, 11, 12],
       [ 0,  0, 15, 16, 17, 18],
       [ 0,  0,  0, 22, 23, 24],
       [ 0,  0,  0,  0, 29, 30],
       [ 0,  0,  0,  0,  0, 36]])

In [36]:
np.tril(arr)

array([[ 1,  0,  0,  0,  0,  0],
       [ 7,  8,  0,  0,  0,  0],
       [13, 14, 15,  0,  0,  0],
       [19, 20, 21, 22,  0,  0],
       [25, 26, 27, 28, 29,  0],
       [31, 32, 33, 34, 35, 36]])

In [37]:
# QUESTION 8

In [38]:
arr=np.arange(20)

In [39]:
arr=arr.reshape(4,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [40]:
arr=arr.reshape(2,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [41]:
arr=arr.reshape(5,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [42]:
# QUESTION 9

In [43]:
arr=np.arange(25).reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
(arr[0:,0:1].sum(),arr[0:,1:2].sum(),arr[0:,2:3].sum())  #ROWS

(np.int64(50), np.int64(55), np.int64(60))

In [45]:
(arr[0:1,0:].sum(),arr[1:2,0:].sum(),arr[2:3,0:].sum(),arr[3:4,0:].sum(),arr[4:5,0:].sum())  #COLUMN

(np.int64(10), np.int64(35), np.int64(60), np.int64(85), np.int64(110))

In [46]:
# QUESTION 10

In [47]:
arr1=np.random.randint(1,50,20)
arr2=np.random.randint(1,50,20)

In [48]:
arr1

array([14, 36, 24, 49, 25, 43, 18, 44,  5, 30, 43, 20, 43, 18, 46, 28, 15,
        7, 17, 36], dtype=int32)

In [49]:
arr2

array([20, 41, 16, 40, 18, 33, 46, 24, 26, 13, 26, 20, 33,  4,  3, 18, 20,
       30, 21, 44], dtype=int32)

In [50]:
com=np.intersect1d(arr1,arr2)
com

array([18, 20, 24, 30, 44, 46], dtype=int32)

In [51]:
# QUESTION 11

In [70]:
arr=np.random.randint(1, 100, (5, 5))
arr

array([[17, 40, 13,  3, 78],
       [30, 75, 56, 56, 91],
       [25,  3, 48, 22, 46],
       [34, 76, 45, 87, 61],
       [57, 61, 75, 85, 15]], dtype=int32)

In [71]:
max_value = np.max(arr)

In [72]:
position = np.unravel_index(np.argmax(arr), arr.shape)

In [74]:
print("\nLargest Element:", max_value)
print("Position (row, column):", position)


Largest Element: 91
Position (row, column): (np.int64(1), np.int64(4))


In [78]:
# student marks dataset

arr=np.array([67,78,97,56,84,51])

print("highest marks:",arr.max())

print("lowest marks:",arr.min())

average=arr.mean()
print("average marks:",average)

above_average=arr[arr>average]
above_average

highest marks: 97
lowest marks: 51
average marks: 72.16666666666667


array([78, 97, 84])